# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccmain.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(292, 406)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/snimki/icons8_estimate_96_H72_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 271, 346))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(12, 188, 247, 145))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.firstC_2 = QtWidgets.QComboBox(self.frame_5)
        self.firstC_2.setObjectName("firstC_2")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/snimki/btc-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firstC_2.addItem(icon1, "")
        self.gridLayout_7.addWidget(self.firstC_2, 0, 0, 1, 1)
        self.firstCINP_2 = QtWidgets.QLineEdit(self.frame_5)
        self.firstCINP_2.setObjectName("firstCINP_2")
        self.gridLayout_7.addWidget(self.firstCINP_2, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        self.exchange_2 = QtWidgets.QPushButton(self.frame_8)
        self.exchange_2.setObjectName("exchange_2")
        self.gridLayout_8.addWidget(self.exchange_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.secondC_2 = QtWidgets.QComboBox(self.frame_7)
        self.secondC_2.setObjectName("secondC_2")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/snimki/1280px-Flag_of_the_United_States.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.secondC_2.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/snimki/eu-flag-png-download-pngwebpjpg-600.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.secondC_2.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/snimki/flag-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.secondC_2.addItem(icon4, "")
        self.gridLayout_10.addWidget(self.secondC_2, 0, 0, 1, 1)
        self.secondCOUT_2 = QtWidgets.QLineEdit(self.frame_7)
        self.secondCOUT_2.setReadOnly(True)
        self.secondCOUT_2.setObjectName("secondCOUT_2")
        self.gridLayout_10.addWidget(self.secondCOUT_2, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_7, 2, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(12, 10, 247, 145))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_2 = QtWidgets.QFrame(self.frame_9)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.firstC = QtWidgets.QComboBox(self.frame_2)
        self.firstC.setObjectName("firstC")
        self.firstC.addItem(icon3, "")
        self.firstC.addItem(icon2, "")
        self.firstC.addItem(icon4, "")
        self.gridLayout_2.addWidget(self.firstC, 0, 0, 1, 1)
        self.firstCINP = QtWidgets.QLineEdit(self.frame_2)
        self.firstCINP.setInputMask("")
        self.firstCINP.setObjectName("firstCINP")
        self.gridLayout_2.addWidget(self.firstCINP, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.exchange = QtWidgets.QPushButton(self.frame_9)
        self.exchange.setObjectName("exchange")
        self.gridLayout_5.addWidget(self.exchange, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_9)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.secondC = QtWidgets.QComboBox(self.frame_3)
        self.secondC.setObjectName("secondC")
        self.secondC.addItem(icon2, "")
        self.secondC.addItem(icon3, "")
        self.secondC.addItem(icon4, "")
        self.gridLayout.addWidget(self.secondC, 0, 0, 1, 1)
        self.secondCOUT = QtWidgets.QLineEdit(self.frame_3)
        self.secondCOUT.setReadOnly(True)
        self.secondCOUT.setObjectName("secondCOUT")
        self.gridLayout.addWidget(self.secondCOUT, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_3, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(70, 162, 120, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSeparator = QtWidgets.QMenu(self.menuFile)
        self.menuSeparator.setObjectName("menuSeparator")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.themes = QtWidgets.QAction(MainWindow)
        self.themes.setCheckable(True)
        self.themes.setObjectName("themes")
        self.btc = QtWidgets.QAction(MainWindow)
        self.btc.setCheckable(True)
        self.btc.setChecked(False)
        self.btc.setObjectName("btc")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actiontext = QtWidgets.QAction(MainWindow)
        self.actiontext.setObjectName("actiontext")
        self.actionDot = QtWidgets.QAction(MainWindow)
        self.actionDot.setCheckable(False)
        self.actionDot.setChecked(False)
        self.actionDot.setObjectName("actionDot")
        self.actionComma = QtWidgets.QAction(MainWindow)
        self.actionComma.setCheckable(False)
        self.actionComma.setChecked(False)
        self.actionComma.setObjectName("actionComma")
        self.menuSeparator.addAction(self.actiontext)
        self.menuSeparator.addSeparator()
        self.menuSeparator.addAction(self.actionDot)
        self.menuSeparator.addAction(self.actionComma)
        self.menuFile.addAction(self.themes)
        self.menuFile.addAction(self.btc)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuSeparator.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qExchanger"))
        self.firstC_2.setItemText(0, _translate("MainWindow", "BTC"))
        self.exchange_2.setText(_translate("MainWindow", "Exchange"))
        self.secondC_2.setItemText(0, _translate("MainWindow", "USD"))
        self.secondC_2.setItemText(1, _translate("MainWindow", "EUR"))
        self.secondC_2.setItemText(2, _translate("MainWindow", "BGN"))
        self.firstC.setItemText(0, _translate("MainWindow", "EUR"))
        self.firstC.setItemText(1, _translate("MainWindow", "USD"))
        self.firstC.setItemText(2, _translate("MainWindow", "BGN"))
        self.exchange.setText(_translate("MainWindow", "Exchange"))
        self.secondC.setItemText(0, _translate("MainWindow", "USD"))
        self.secondC.setItemText(1, _translate("MainWindow", "EUR"))
        self.secondC.setItemText(2, _translate("MainWindow", "BGN"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSeparator.setTitle(_translate("MainWindow", "Separator"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.themes.setText(_translate("MainWindow", "Dark Mode"))
        self.btc.setText(_translate("MainWindow", "BTC"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actiontext.setText(_translate("MainWindow", "Choose a default separator"))
        self.actionDot.setText(_translate("MainWindow", "Dot"))
        self.actionComma.setText(_translate("MainWindow", "Comma"))


import icons_rc
